import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="pt-16"
      >
      <h1>Hello World</h1>
        <Link
            className="text-2xl underline font-bold"
            href={"/play"}>Game</Link>
      </div>
    </>
  )
}
